<?php


class AitHiddenOptionControl extends AitOptionControl
{


	protected function init()
	{
		$this->isCloneable = true;
	}



    public function getHtml()
    {
    	// you can use hidden input for example in clone items as identifier.
    	// uuid will be generated by javascript when hidden input is created
    	$generateUUID = false;
    	if (isset($this->config->uuid)) {
    		$generateUUID = $this->config->uuid;
    	}
		ob_start();
		?>
        <input type="hidden" name="<?php echo $this->getNameAttr() ?>" value="<?php echo esc_attr($this->getValue()); ?>" data-uuid="<?php echo $generateUUID; ?>">
		<?php
		return ob_get_clean();
    }

}
